dependencies:
  - allOf:
      - naiserator
environmentKinds:
  - onprem
  - legacy
  - tenant
values:
  apiServerCIDR:
    description: CIDR for the API server
    displayName: API server CIDR
    config:
      type: string
  image.tag:
    displayName: Image tag
    config:
      type: string
