dependencies:
  - allOf:
      - naiserator
environmentKinds:
  - onprem
  - legacy
  - tenant
values:
  apiServerCIDR:
    displayName: API server cidr
    computed:
      template: '"{{ .Env.apiserver_endpoint }}/32"'
  image.tag:
    displayName: Image tag
    config:
      type: string
