name: Build and deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

env:
  NAME: hahaha
  FEATURE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais/feature

jobs:
  build_and_push:
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    permissions:
      contents: "read"
      id-token: "write"
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: ${{ env.NAME }}
          google_service_account: gh-${{ env.NAME }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          multi-platform: true
          push: "${{ github.ref == 'refs/heads/main' }}"

      - uses: azure/setup-helm@v3
        name: "Setup Helm"
        with:
          version: "v3.12.0"

      - name: Build Chart
        run: |-
          yq e '.version = "${{ steps.build-push-sign.outputs.version }}"' --inplace "charts/Chart.yaml"
          yq e '.image.tag = "${{ steps.build-push-sign.outputs.version }}"' --inplace "charts/values.yaml"
          helm package charts

      - name: Push Chart
        if: github.ref == 'refs/heads/main'
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.FEATURE_REPOSITORY }}

  rollout:
    if: github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main'
    needs:
      - build_and_push
    runs-on: fasit-deploy
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@v2
        with:
          chart: ${{ env.FEATURE_REPOSITORY }}/${{ env.NAME }}
          version: ${{ needs.build_and_push.outputs.version }}
          feature_name: ${{ env.NAME }}
